### ISSUE TITLE
[FEATURE] Give Warning About Possible Antivirus Activity Upon Downloading Top 100 Repos

### ISSUE THREAD

**Issue by Danc2050** [IntelLabs/control-flag#39]
This project may want to give a warning that the top 100 repos may trigger the antivirus that is local to the computer for malware/pentest-type repositories. For example, upon downloading this, I had this many quarantined items in my antivirus:
![image](https://user-images.githubusercontent.com/32185616/147846564-5e11581d-2235-41a2-97e5-4234c4243fda.png)

**Comment by nhasabni** [comment]
Thanks for the report. Yes, I will add the warning to the documentation so that such an activity would not be surprising.
